<?php

namespace Aventura\Wprss\Core\Block;

use Aventura\Wprss\Core;

/**
 * Basic functionality for all blocks.
 *
 * @since 4.9
 */
abstract class AbstractBlock extends Core\Model\ModelAbstract implements BlockInterface
{
    /**
     * {@inheritdoc}
     * @since 4.9
     */
    public function __toString() {
        return $this->getOutput();
    }

    /**
     * A more structured way of retrieving this block's output.
     *
     * @since 4.9
     * @return string Output generated by this block.
     */
    abstract public function getOutput();
}
