<?php
namespace Aventura\Wprss\Core\Block;

/**
 * Something that can be a block.
 *
 * A block is a class that is responsible for generating output.
 *
 * @since [*next-version*]
 */
interface BlockInterface {

    /**
     * Retrieve the string output of this block.
     *
     * @since [*next-version*]
     * @return string The output generated by this block.
     */
    public function __toString();
}
